version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: artevida_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: artevida_cultural
      MYSQL_USER: readonly_user
      MYSQL_PASSWORD: readonly_pass123
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: